baseurl = "https://www.bluelife.at"
title = "bluelife"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
    author = "Bernhard Fröhlich"
    info = "Software developer and full time geek"
    description = "Personal blog of a Software developer and full time geek"
    keywords = "blog,personal"
    avatarurl = "/images/decke.jpeg"

    favicon_32 = "/favicon.png"
    footercontent = "<a href=\"/contact/#privacy\">Privacy Policy</a> | <a href=\"/index.xml\">RSS Feed</a>"

    hidecredits = true
    hidecopyright = true
    rtl = false
    math = false

# Posts
[taxonomies]
  category = "categories"
  tag = "tags"

[permalinks]
  posts = "/:slug/"
  page = "/:slug/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Network"
    weight = 2
    identifier = "network"
    url = "/network/"
[[menu.main]]
    name = "Code"
    weight = 3
    identifier = "code"
    url = "https://codeberg.org/decke"
[[menu.main]]
    name = "Contact"
    weight = 4
    identifier = "contact"
    url = "/contact/"
[[menu.main]]
    name = "About"
    weight = 5
    url = "/about/"
