[build]
publish = "public"
command = "make deploy"

[context.production.environment]
HUGO_VERSION = "0.72.0"
HUGO_ENV = "production"

[[headers]]
  for ="/*"

  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = "default-src 'none'; font-src 'self'; img-src 'self' data:image/svg+xml; script-src 'self'; style-src 'self'; base-uri 'none'; form-action 'none'"
